### ISSUE TITLE
PubSub commands limited to single argument

### ISSUE THREAD

**Issue by sm2017** [clue/php-redis-react#75] opened 2018-03-13 13:03 UTC
I think https://github.com/clue/php-redis-react/blob/master/src/StreamingClient.php#L89 is wrong

According to https://redis.io/commands/subscribe , You can ` SUBSCRIBE channel [channel ...] ` , you can subscribe multiple channel in single command , So https://github.com/clue/php-redis-react/blob/master/src/StreamingClient.php#L84 must be empty

**Comment by clue** [comment] 2018-03-13 15:02
Thank you for reporting this feature request. While this is currently by design, I agree that this is something that should either be implemented or at least documented accordingly.

The `SUBSCRIBE`-family of commands do not follow request-response semantics anymore if not called with exactly one parameter. It was thus limited to only accept a single argument per invocation as originally implemented in #24.

As an alternative, you can simply call `SUBSCRIBE`-family of commands any number of times with one argument each.

Other than that, there are currently no immediate plans to build this from my end (no demand at the moment), but I would be really happy to accept PRs :+1: 

*(If you need this for a commercial project and you want a quote, please check out my profile and send me an email)*

I hope this helps and you understand I'm closing this ticket for now. If your problem persists and you feel this is an issue that targets a broader audience, please comment back and we can re-open this. :+1:

**Closed by clue** 2018-03-13 15:02 UTC
Labels: help wanted, new feature
