### ISSUE TITLE
Assosiative array serializer

### ISSUE THREAD

**Issue by sm2017** [clue/php-redis-react#44] opened 2017-02-23 06:12 UTC
Hi

I want to cache result of mysql queries in redis , As I use MYSQLI_ASSOC my data is in associative array format , So converting associative array to pass it to Clue\Redis is not optimize

Can you please implement Assosiative array serializer so we can do like this 

```php
 $client->HSET('myhash',[
    'field1' => 'hello',
    'field2' => 'world',
]);
```

No I must convert it to ['field1','hello','field2','world'] and then 
```php
 $client->HSET('myhash',... ['field1','hello','field2','world']);
```

**Comment by sm2017** [comment] 2017-02-25 08:40
Help please

**Comment by clue** [comment] 2017-02-27 15:38
Duplicate of #17

**Closed by clue** 2017-02-27 15:38 UTC
